# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ALL_INSTALL_TYPES "Full")
set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_INNOSETUP "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer;C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/build_verify")
set(CPACK_CMAKE_GENERATOR "Visual Studio 17 2022")
set(CPACK_COMPONENTS_ALL "applications")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_APPLICATIONS_DESCRIPTION "A free and open source ISO11783-10 Task Controller Server")
set(CPACK_COMPONENT_APPLICATIONS_DISPLAY_NAME "AgIsoTaskControllerServer")
set(CPACK_COMPONENT_APPLICATIONS_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_DEFAULT_INSTALL_TYPES "")
set(CPACK_COMPONENT_LIBRARIES_INSTALL_TYPES "Full")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "AgIsoTaskControllerServer built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/build_verify;AgIsoTaskControllerServer;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/AgIsoTaskControllerServer")
set(CPACK_MODULE_PATH "C:/Qt/6.5.3/msvc2019_64/lib/cmake/Qt6;C:/Qt/6.5.3/msvc2019_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;C:/Qt/6.5.3/msvc2019_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_CONTACT "delgrossoengineering@protonmail.com")
set(CPACK_NSIS_DISPLAY_NAME "AgIsoTaskControllerServer")
set(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
set(CPACK_NSIS_INSTALLED_ICON_NAME "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/doc/logo.ico")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_MUI_ICON "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/doc/logo.ico")
set(CPACK_NSIS_MUI_UNICON "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/doc/logo.ico")
set(CPACK_NSIS_PACKAGE_NAME "AgIsoTaskControllerServer")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/build_verify/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "delgrossoengineering@protonmail.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "An ISO11783-10 Task Controller Server")
set(CPACK_PACKAGE_EXECUTABLES "AgIsoTaskControllerServer;AgIsoTaskControllerServer")
set(CPACK_PACKAGE_FILE_NAME "AgIsoTaskControllerServer-0.1.0-win64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "AgIsoTaskControllerServer")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "AgIsoTaskControllerServer")
set(CPACK_PACKAGE_NAME "AgIsoTaskControllerServer")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Open-Agriculture")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-4.4/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-4.4/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/build_verify/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/gr_efr/Documents/prv_sw_dev/AgIsoTaskControllerServer/build_verify/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
